### ISSUE TITLE
add keyboard shortcuts for start/stop/pause/reset

### ISSUE THREAD

**Issue by cantonadong** [swharden/BasicTimer#5]
hi author, this app is fantasic for me to helping my presentation rehearal.
and thank you very much for developing this app.

can i propose some advice for this app?

1. add keyboard control,like SPACE for start/pause, ENTER for reset.
2. add COUNTDOWN, set a customized time to countdown.

**Comment by swharden** [comment]
Hi @cantonadong, thank you for these suggestions! I will split these ideas into two issues and address them individually 👍 

* #5
* #6
